
---
  task : BinaryClassification
  optimizer : SGD
  train_batch_size : 32
  test_batch_size : 1
  train_epochs : 200
  lr : 0.01
  diff_privacy: True
  MAX_GRAD_NORM: 1.0
  EPSILON: 20.0
  DELTA: 1e-5
  num_rounds: 100
  min_evalclient: 2
  # path_to_master_csv : 'D:\ESI\3CS\PFE\last_year\Code\MEDfl\notebooks\sapsii_score_knnimputed_eicu.csv'
  path_to_master_csv : '/home/local/USHERBROOKE/saho6810/MEDfl/code/MEDfl/notebooks/data/masterDataSet/Mimic_ouael.csv'
  
  path_to_test_csv : '/home/local/USHERBROOKE/saho6810/MEDfl/code/MEDfl/notebooks/data/masterDataSet/Mimic_train.csv'

...


