DELTA: 1.0e-05
EPSILON: 5.0
MAX_GRAD_NORM: 1.0
diff_privacy: true
lr: 0.001
min_evalclient: 2
num_rounds: 20
optimizer: SGD
path_to_master_csv: /home/local/USHERBROOKE/saho6810/MEDfl/code/MEDfl/notebooks/data/masterDataSet/miniDiabete.csv
path_to_test_csv: /home/local/USHERBROOKE/saho6810/MEDfl/code/MEDfl/notebooks/data/masterDataSet/Mimic_train.csv
task: BinaryClassification
test_batch_size: 1
train_batch_size: 32
train_epochs: 20
